from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.String(36), primary_key=True), sa.Column("email", sa.String(255), nullable=False, unique=True), sa.Column("full_name", sa.String(200), nullable=False), sa.Column("password_hash", sa.String(500), nullable=False), sa.Column("role", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("cases", sa.Column("id", sa.String(36), primary_key=True), sa.Column("case_number", sa.String(100), nullable=False, unique=True), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("case_type", sa.String(100), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("created_by", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("case_members", sa.Column("id", sa.String(36), primary_key=True), sa.Column("case_id", sa.String(36), sa.ForeignKey("cases.id"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("permission", sa.String(30), nullable=False))
    op.create_table("documents", sa.Column("id", sa.String(36), primary_key=True), sa.Column("case_id", sa.String(36), sa.ForeignKey("cases.id"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("content_type", sa.String(120), nullable=False), sa.Column("classification", sa.String(120), nullable=False), sa.Column("latest_version", sa.Integer(), nullable=False), sa.Column("created_by", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("document_versions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("document_id", sa.String(36), sa.ForeignKey("documents.id"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("storage_name", sa.String(255), nullable=False, unique=True), sa.Column("encrypted_dek", sa.Text(), nullable=False), sa.Column("nonce", sa.String(64), nullable=False), sa.Column("encrypted_hash", sa.String(64), nullable=False), sa.Column("plaintext_hash", sa.String(64), nullable=False), sa.Column("analysis_json", sa.Text(), nullable=False), sa.Column("blockchain_tx", sa.String(255)), sa.Column("signature", sa.String(64), nullable=False), sa.Column("created_by", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("access_grants", sa.Column("id", sa.String(36), primary_key=True), sa.Column("document_id", sa.String(36), sa.ForeignKey("documents.id"), nullable=False), sa.Column("recipient_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("permission", sa.String(30), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("one_time", sa.Boolean(), nullable=False), sa.Column("used_at", sa.DateTime(timezone=True)), sa.Column("created_by", sa.String(36), sa.ForeignKey("users.id"), nullable=False))
    op.create_table("audit_events", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id")), sa.Column("case_id", sa.String(36)), sa.Column("document_id", sa.String(36)), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("data_json", sa.Text(), nullable=False), sa.Column("previous_hash", sa.String(64), nullable=False), sa.Column("event_hash", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("refresh_tokens", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("replaced_by", sa.String(64)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))

def downgrade():
    for table in ("refresh_tokens", "audit_events", "access_grants", "document_versions", "documents", "case_members", "cases", "users"):
        op.drop_table(table)
